### PR TITLE
RegEx'es splitting

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by Piterden** [comment]
Okay.

Btw, you can integrate CI tests right here

**Comment by dfahlander** [comment]
I've no access to lib's settings. Maybe @ignasbernotas could assist by either set me as admin or integrate travis?

**Comment by ignasbernotas** [comment]
Hmm, appears that only organizations can have multi-level permissions, at the moment it's either collaborator or owner. I'd be happy to transfer the repo to you if you like, otherwise I'll set up Travis over the weekend:)

**Comment by dfahlander** [comment]
@ignasbernotas Is it possible to add me as owner, or is a transfer required? Regarding travis, if you just visit https://travis-ci.org and search up this lib, I think it guides you very quickly on how to enable it step by step. Once it is enabled, any collaborator may integrate it further (such as adding karma to automate the browser tests)

**Comment by ignasbernotas** [comment]
Travis is set up. However I don't seem to see a way to trigger it retrospectively for this PR. I'll look into more.

**Pull request closed without merging**
