### PR TITLE
Optimized query and added browser-based tests

### PR DESCRIPTION
**Pull request by dfahlander**

### CODE REVIEW

**Comment by ignasbernotas** [comment]
Awesome! However it still looks like the distributable file has a lot of overhead in terms of all the webpack stuff, I saw that Dexie doesn't use webpack (not sure why I even needed it) and the compiled files have multiple versions for different environments, what do you think the best way to achieve a similar result with the plugin would be? I think we should provide a node and web (minified) versions in the dist folder. Does that make sense to you? :)

**Comment by dfahlander** [comment]
Sure. I use rollupjs in place of webpack. Much smaller footprint. There's a babel alternative called Buble from the author of rollupjs that is simpler and produces less code. I think we could give it a try and produce dist versions similar to those of Dexie.Syncable.

**Comment by dfahlander** [comment]
PS...  aren't you going to merge the PR ?

**Comment by ignasbernotas** [comment]
haha, yeah, sorry I was just looking into the distribution, but I think we're good to go for now :) Thanks for the awesome work!

**Pull request merged**
