### PR TITLE
Foreign key is nullable

### LINKED ISSUE #25: When foreign key is null, we get an error
`Could not lookup foreign key where ... The content of the failing key was: null.`

In my opinion the relation property should just be null there.

### PR DESCRIPTION
**Pull request by tdesvenain**
Fixes #25

### CODE REVIEW

**Comment by tdesvenain** [comment]
Hi @dfahlander  what is the procedure to run all-browser-test.js ?

**Comment by dfahlander** [comment]
Thanks for looking into this ;)
Procedure for browser tests are (as we still don' use karma):
1. npm test (just to build everything)
2. http-server -c-1 . (or use a similar http server tool)
3. Browse to the testrunner.html

**Comment by tdesvenain** [comment]
Thanks @dfahlander, tests are updated, pr is now ready for review

**Comment by dfahlander** [comment]
Many Thanks! I hope to have a chance to go through it tomorrow.

**Pull request merged**
